name: build development images

on:
  push:
    branches:
      - dev

env:
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_REGISTRY_LOGIN: "dockerhub.ebi.ac.uk"
  SINGULARITY_REGISTRY_LOGIN: "oras://dockerhub.ebi.ac.uk"
  DOCKER_REGISTRY: "dockerhub.ebi.ac.uk/gdp-public/pgsc_calc"
  SINGULARITY_REGISTRY: "oras://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity"
  SINGULARITY_VERSION: "3.8.3"

jobs:
  build_docker_dev:
    name: build docker development image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/pgscatalog_utils' }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: docker build --no-cache . -t "${DOCKER_REGISTRY}/pgscatalog_utils:dev"

      - name: Push image
        run: |
          echo "$REGISTRY_TOKEN" | docker login "$DOCKER_REGISTRY_LOGIN" -u "$REGISTRY_USERNAME" --password-stdin
          docker push "${DOCKER_REGISTRY}/pgscatalog_utils:dev"

  build_singularity_dev:
    needs: build_docker_dev
    name: build singularity development image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/pgscatalog_utils' }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Cache singularity setup
        id: cache-singularity
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64
          key: ${{ runner.os }}-singularity-${{ env.SINGULARITY_VERSION }}

      # set up singularity checks for cache automatically
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: ${{ env.SINGULARITY_VERSION }}

      - name: Build singularity image
        run: singularity build img.sif "docker://${DOCKER_REGISTRY}/pgscatalog_utils:dev"

      - name: Push singularity image
        run: |
          echo "$REGISTRY_TOKEN" | singularity remote login -u "$REGISTRY_USERNAME" --password-stdin "$SINGULARITY_REGISTRY_LOGIN"
          singularity push img.sif "${SINGULARITY_REGISTRY}/pgscatalog_utils:dev"
