name: build singularity development image

on:
  workflow_run:
    workflows: [build docker development image]
    types:
      - completed
      
jobs:
  build_singularity_dev:
    name: build singularity development image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/pgscatalog_utils' }}
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2
        
      - name: Cache singularity setup
        id: cache-singularity
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/singularity/
          key: ${{ runner.os }}-singularity
        
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        if: steps.cache-singularity.outputs.cache-hit != 'true'        
        with:
          singularity-version: 3.8.3        

      - name: Build singularity docker iamge
        run: singularity build img.sif docker://dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/pgscatalog_utils:latest

      - name: Push singularity docker image
        run: |
          echo "$DOCKER_TOKEN" | singularity remote login -u "$DOCKER_USERNAME" --password-stdin oras://gitlab.ebi.ac.uk
          singularity push img.sif dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/singularity/pgscatalog_utils:amd64-${{ github.event.release.tag_name }}
