name: build docker development image

on:
  push:
    branches:
      - dev  

jobs:
  build_docker_dev:
    name: build development docker image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'pgscatalog/pgscatalog_utils' }}
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2
          
      - name: Build new docker image
        run: docker build --no-cache . -t dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/pgscatalog_utils:dev

      - name: Push image
        run: |
          echo "$DOCKER_TOKEN" | docker login dockerhub.ebi.ac.uk -u "$DOCKER_USERNAME" --password-stdin
          docker push dockerhub.ebi.ac.uk/gdp-public/pgsc_calc/pgscatalog_utils:dev          
